/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    customers: CustomerAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    customers: Customer;
    media: Media;
    products: Product;
    orders: Order;
    'product-reviews': ProductReview;
    'hero-banners': HeroBanner;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'product-reviews': ProductReviewsSelect<false> | ProductReviewsSelect<true>;
    'hero-banners': HeroBannersSelect<false> | HeroBannersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('tr' | 'en') | ('tr' | 'en')[];
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'tr' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Customer;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface CustomerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  name?: string | null;
  phone?: string | null;
  city?: string | null;
  district?: string | null;
  /**
   * Mahalle, sokak, bina, daire — kargo teslimatı için.
   */
  address?: string | null;
  postalCode?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'customers';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Görsel/video açıklaması (erişilebilirlik).
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  /**
   * Benzersiz stok kodu. Boş bırakırsan otomatik SN-XXXXXXXXX üretilir.
   */
  sku: string;
  slug: string;
  brand: string;
  shortDescription: string;
  /**
   * Kalın yazı, liste ve link destekler (Lexical).
   */
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Her bölüm: Başlık + Detay. TR/EN için üstteki dil seçicisini kullan.
   */
  detailSections?:
    | {
        /**
         * Sitede bölüm başlığı olur. Varsayılan: Cihaz hakkında
         */
        title: string;
        /**
         * Kalın yazı, liste, link. Sitede başlığın altında çıkar.
         */
        body: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  faqs?:
    | {
        question: string;
        answer: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  features?: string[] | null;
  price: number;
  currency: string;
  stockQty: number;
  /**
   * false ise satışa kapalı. stockQty 0 olunca otomatik kapanır.
   */
  inStock?: boolean | null;
  /**
   * İşaretlenen ürünler anasayfa vitrininde çıkar.
   */
  featuredOnHome?: boolean | null;
  /**
   * Küçük sayı önce gösterilir.
   */
  featuredOrder?: number | null;
  accent?: string | null;
  image?: (number | null) | Media;
  /**
   * Kapak dışındaki ek ürün görselleri (Media’ya yüklenmiş).
   */
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Upload yoksa kullanılır (eski Rozetka URL’leri).
   */
  imageUrl?: string | null;
  images?: string[] | null;
  sourcePriceUah?: number | null;
  sourceUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderNumber: string;
  /**
   * Sipariş sayfası erişim token’ı (URL ?t=)
   */
  accessToken: string;
  customer?: (number | null) | Customer;
  status: 'pending' | 'paid' | 'shipped' | 'delivered' | 'cancelled' | 'wrong_amount';
  total: number;
  currency: string;
  customerName: string;
  customerEmail: string;
  customerPhone: string;
  customerAddress: string;
  customerCity: string;
  customerNote?: string | null;
  trackingNumber?: string | null;
  carrier?: string | null;
  cryptomusInvoiceUuid?: string | null;
  cryptomusPaymentUrl?: string | null;
  items: {
    productId: string;
    name: string;
    price: number;
    quantity: number;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * Onaylı (approved) yorumlar sitede görünür. Kullanıcı yorumları pending gelir — buradan onayla.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-reviews".
 */
export interface ProductReview {
  id: number;
  product: number | Product;
  rating: number;
  title?: string | null;
  body: string;
  authorName: string;
  /**
   * Boşsa seed / manuel yorum olabilir.
   */
  customer?: (number | null) | Customer;
  status: 'pending' | 'approved' | 'rejected';
  /**
   * Seed yorumlarda ‘satın aldı’ rozeti gösterilmez.
   */
  source: 'user' | 'seed';
  locale?: ('tr' | 'en') | null;
  verifiedPurchase?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Anasayfa hero slide’ları. Sadece görsel de ekleyebilirsin — başlık/CTA zorunlu değil. Sıra: küçük sayı önce.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-banners".
 */
export interface HeroBanner {
  id: number;
  active?: boolean | null;
  /**
   * Küçük sayı önce gösterilir.
   */
  order?: number | null;
  /**
   * JPG/PNG/WebP/AVIF veya MP4/WebM. Önerilen görsel: 1920×1080. Video: kısa, sessiz loop (max ~15–20MB). TR/EN dil seçicisi.
   */
  image?: (number | null) | Media;
  /**
   * JPG/PNG/WebP veya MP4. Önerilen: 768×1200. Boşsa desktop kullanılır.
   */
  imageMobile?: (number | null) | Media;
  /**
   * Upload yoksa (CDN). Görsel veya .mp4/.webm URL olabilir.
   */
  imageUrl?: string | null;
  /**
   * Mobil upload yoksa. Görsel veya video URL.
   */
  imageUrlMobile?: string | null;
  /**
   * Görsel / fiyat / CTA link için yedek. Serbest alanlar önceliklidir.
   */
  product?: (number | null) | Product;
  showPrice?: boolean | null;
  /**
   * Boş bırakılabilir (sadece görsel banner). Enter ile satır kırılır.
   */
  title?: string | null;
  subtitle?: string | null;
  /**
   * Boş bırakılırsa rozet gösterilmez.
   */
  badge?: string | null;
  badgeTone?: ('accent' | 'success' | 'danger' | 'muted') | null;
  /**
   * Boşsa buton gösterilmez.
   */
  ctaLabel?: string | null;
  /**
   * Boşsa ürün seçiliyse /urun/slug, değilse /urunler
   */
  ctaHref?: string | null;
  secondaryLabel?: string | null;
  secondaryHref?: string | null;
  /**
   * Tüm slide’lar full-bleed arka plan. Metin yoksa sadece görsel.
   */
  layout: 'textOverlay' | 'textLeft' | 'textRight';
  titleSize?: ('sm' | 'md' | 'lg' | 'xl') | null;
  subtitleSize?: ('sm' | 'md' | 'lg') | null;
  titleAlign?: ('left' | 'center') | null;
  titleUppercase?: boolean | null;
  /**
   * hex veya oklch. Boş = varsayılan Kriptostore teması
   */
  gradientFrom?: string | null;
  gradientTo?: string | null;
  accentGlow?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'hero-banners';
        value: number | HeroBanner;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  city?: T;
  district?: T;
  address?: T;
  postalCode?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  sku?: T;
  slug?: T;
  brand?: T;
  shortDescription?: T;
  description?: T;
  detailSections?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  features?: T;
  price?: T;
  currency?: T;
  stockQty?: T;
  inStock?: T;
  featuredOnHome?: T;
  featuredOrder?: T;
  accent?: T;
  image?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  imageUrl?: T;
  images?: T;
  sourcePriceUah?: T;
  sourceUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  accessToken?: T;
  customer?: T;
  status?: T;
  total?: T;
  currency?: T;
  customerName?: T;
  customerEmail?: T;
  customerPhone?: T;
  customerAddress?: T;
  customerCity?: T;
  customerNote?: T;
  trackingNumber?: T;
  carrier?: T;
  cryptomusInvoiceUuid?: T;
  cryptomusPaymentUrl?: T;
  items?:
    | T
    | {
        productId?: T;
        name?: T;
        price?: T;
        quantity?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-reviews_select".
 */
export interface ProductReviewsSelect<T extends boolean = true> {
  product?: T;
  rating?: T;
  title?: T;
  body?: T;
  authorName?: T;
  customer?: T;
  status?: T;
  source?: T;
  locale?: T;
  verifiedPurchase?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-banners_select".
 */
export interface HeroBannersSelect<T extends boolean = true> {
  active?: T;
  order?: T;
  image?: T;
  imageMobile?: T;
  imageUrl?: T;
  imageUrlMobile?: T;
  product?: T;
  showPrice?: T;
  title?: T;
  subtitle?: T;
  badge?: T;
  badgeTone?: T;
  ctaLabel?: T;
  ctaHref?: T;
  secondaryLabel?: T;
  secondaryHref?: T;
  layout?: T;
  titleSize?: T;
  subtitleSize?: T;
  titleAlign?: T;
  titleUppercase?: T;
  gradientFrom?: T;
  gradientTo?: T;
  accentGlow?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * İletişim, adres ve yasal sayfa metinleri (Gizlilik, TOS, İade, KVKK). Sitede anında yansır.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  companyLegalName: string;
  contactEmail: string;
  contactPhone?: string | null;
  /**
   * Uluslararası format, örn. +905xxxxxxxxx
   */
  whatsapp?: string | null;
  supportHours?: string | null;
  contactPageTitle?: string | null;
  contactPageIntro?: string | null;
  addressLine1: string;
  addressLine2?: string | null;
  city: string;
  state: string;
  postalCode: string;
  country: string;
  privacyTitle?: string | null;
  /**
   * Kalın yazı, liste ve link destekler. TR/EN için üstteki dil seçicisini kullanın.
   */
  privacyBody?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  termsTitle?: string | null;
  /**
   * Kalın yazı, liste ve link destekler. TR/EN için üstteki dil seçicisini kullanın.
   */
  termsBody?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  returnsTitle?: string | null;
  /**
   * Kalın yazı, liste ve link destekler. TR/EN için üstteki dil seçicisini kullanın.
   */
  returnsBody?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  kvkkTitle?: string | null;
  /**
   * Kalın yazı, liste ve link destekler. TR/EN için üstteki dil seçicisini kullanın.
   */
  kvkkBody?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Yasal sayfalarda ve moderasyon metninde gösterilir.
   */
  productOrigin?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  companyLegalName?: T;
  contactEmail?: T;
  contactPhone?: T;
  whatsapp?: T;
  supportHours?: T;
  contactPageTitle?: T;
  contactPageIntro?: T;
  addressLine1?: T;
  addressLine2?: T;
  city?: T;
  state?: T;
  postalCode?: T;
  country?: T;
  privacyTitle?: T;
  privacyBody?: T;
  termsTitle?: T;
  termsBody?: T;
  returnsTitle?: T;
  returnsBody?: T;
  kvkkTitle?: T;
  kvkkBody?: T;
  productOrigin?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}